[build]
  publish = "dist/"
  command = "npm run build:app"
  ignore = "[[ $HEAD == main ]]"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[[redirects]]
  from = "/tera/*"
  to = "https://fluid-earth.byrd.osu.edu/tera/:splat"
  status = 200
  force = true
