name: Fluid Earth Tera Status Check
on:
  schedule:
    - cron: '38 * * * *'
  workflow_dispatch:
jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check if Fluid Earth Tera backend is up and up-to-date
        run: $GITHUB_WORKSPACE/backend/scripts/status.js
